### ISSUE TITLE
issue di npm run dev, sudah npm install

### ISSUE THREAD

**Issue by wahyono17** [anvie/leak-checker#2]
> [PWA] PWA support is disabled
error - ./context/WASM.tsx:16:25
Module not found: Can't resolve '../wasm/pkg'
  14 |     console.log("loading wasm context...");
  15 |     (async() => {
> 16 |       const wasm = await import('../wasm/pkg');
     |                         ^
  17 |       await wasm.default()
  18 |       setState({ wasm })
  19 |     })()

Import trace for requested module:
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
wait  - compiling /_error (client and server)...
error - ./context/WASM.tsx:16:25

**Comment by anvie** [comment]
coba ketik `yarn build:wasm` dulu sebelum `yarn dev`:

**Comment by anvie** [comment]
Sudah saya tambahkan ke repo precompiled wasm-nya.
